HTTPSERVER: types.h File Reference
types.h File Reference
#include "def.h"
Functions
char * get_filename_ext (char *filename)
Returns the extension of the filename or null.
char * get_content_type (char *filename)
By using the get_filename_ext, this function returns the content_type of the given filename.
Function Documentation
char* get_content_type (char * filename)
By using the get_filename_ext, this function returns the content_type of the given filename.
Parameters
filename Filename to find it's content-type.
Returns
Filename's content-type.
References get_filename_ext().
Referenced by responseGet().
{
         char *ext = get_filename_ext(filename);
         if (strcmp(ext, "txt") == 0 || strcmp(ext, "sed") == 0
                         || strcmp(ext, "awk") == 0 || strcmp(ext, "c") == 0
                         || strcmp(ext, "h") == 0) {
                 return ("text/plain");
         }
         if (strcmp(ext, "html") == 0 || strcmp(ext, "htm") == 0) {
                 return ("text/html");
         }
         if (strcmp(ext, "jpeg") == 0 || strcmp(ext, "jpg") == 0) {
                 return ("image/jpeg");
         }
         if (strcmp(ext, "png") == 0) {
                 return ("image/png");
         }
         if (strcmp(ext, "css") == 0) {
                 return ("text/css");
         }
         if (strcmp(ext, "js") == 0) {
                 return ("text/javascript");
         }
         if (strcmp(ext, "gif") == 0) {
                 return ("image/gif");
         }
         if (strcmp(ext, "pdf") == 0) {
                 return ("application/pdf");
         }
         return "application/octet-stream";
 }
char* get_filename_ext (char * filename)
Returns the extension of the filename or null.
Parameters
filename Filename to find it's extension.
Returns
Filename's extension or null.
Referenced by get_content_type().
{
         char *dot = strrchr(filename, '.');
         if (!dot || dot == filename)
                 return "";
         return dot + 1;
 }